// <auto-generated />
using System;
using AI.DocumentAssistant.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Pgvector;

#nullable disable

namespace AI.DocumentAssistant.Server.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260904102949_AddHybridRetrievalIndexes")]
    partial class AddHybridRetrievalIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "UpdatedAtUtc");

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.ConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "Sequence")
                        .IsUnique();

                    b.ToTable("ConversationMessages", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.ConversationMessageSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("ConversationMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DocumentChunkId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Heading")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("PageEnd")
                        .HasColumnType("integer");

                    b.Property<int?>("PageStart")
                        .HasColumnType("integer");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("SourceIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConversationMessageId", "SourceIndex")
                        .IsUnique();

                    b.ToTable("ConversationMessageSources", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ChunkedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChunkingError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EmbeddedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmbeddedChunkCount")
                        .HasColumnType("integer");

                    b.Property<int?>("EmbeddingDimensions")
                        .HasColumnType("integer");

                    b.Property<string>("EmbeddingError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EmbeddingModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("ExtractedCharacterCount")
                        .HasColumnType("bigint");

                    b.Property<int>("ExtractedSectionCount")
                        .HasColumnType("integer");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("NormalizationChangedSectionCount")
                        .HasColumnType("integer");

                    b.Property<string>("NormalizationError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("NormalizationRemovedCharacterCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("NormalizedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("NormalizedCharacterCount")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessingError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ProcessingStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "CreatedAtUtc");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CharacterCount")
                        .HasColumnType("integer");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EmbeddedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)");

                    b.Property<string>("EmbeddingContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("EmbeddingDimensions")
                        .HasColumnType("integer");

                    b.Property<string>("EmbeddingModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("PageEnd")
                        .HasColumnType("integer");

                    b.Property<int?>("PageStart")
                        .HasColumnType("integer");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "simple")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Content" });

                    b.Property<string>("SectionTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SourceSectionEndIndex")
                        .HasColumnType("integer");

                    b.Property<int>("SourceSectionStartIndex")
                        .HasColumnType("integer");

                    b.Property<int>("TokenCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("IX_DocumentChunks_SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("DocumentId", "ChunkIndex")
                        .IsUnique();

                    b.ToTable("DocumentChunks", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.DocumentMetadataEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<Guid>("DocumentUnderstandingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentUnderstandingId", "Sequence")
                        .IsUnique();

                    b.HasIndex("Kind", "Label");

                    b.ToTable("DocumentMetadataEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_DocumentMetadataEntries_Confidence", "\"Confidence\" IS NULL OR (\"Confidence\" >= 0 AND \"Confidence\" <= 1)");
                        });
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.DocumentOcrAnalysis", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("CandidatePageCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConfigurationHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EngineName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EngineVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("FailedPageCount")
                        .HasColumnType("integer");

                    b.Property<string>("Languages")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("MaxCandidatePages")
                        .HasColumnType("integer");

                    b.Property<long?>("MaxRenderedPixels")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RenderDpi")
                        .HasColumnType("integer");

                    b.Property<string>("RoutingHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RoutingVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceFileHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SuccessfulPageCount")
                        .HasColumnType("integer");

                    b.HasKey("DocumentId");

                    b.ToTable("DocumentOcrAnalyses", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.DocumentPageOcrResult", b =>
                {
                    b.Property<Guid>("DocumentOcrAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("EffectiveRenderDpi")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double?>("MeanConfidence")
                        .HasColumnType("double precision");

                    b.Property<long?>("ProcessingDurationMs")
                        .HasColumnType("bigint");

                    b.Property<int>("RecognizedCharacterCount")
                        .HasColumnType("integer");

                    b.Property<int>("RecognizedWordCount")
                        .HasColumnType("integer");

                    b.Property<int?>("RenderedHeightPixels")
                        .HasColumnType("integer");

                    b.Property<int?>("RenderedWidthPixels")
                        .HasColumnType("integer");

                    b.Property<string>("SourceTechnicalType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("UsedInExtraction")
                        .HasColumnType("boolean");

                    b.HasKey("DocumentOcrAnalysisId", "PageNumber");

                    b.ToTable("DocumentPageOcrResults", null, t =>
                        {
                            t.HasCheckConstraint("CK_DocumentPageOcrResults_MeanConfidence", "\"MeanConfidence\" IS NULL OR (\"MeanConfidence\" >= 0 AND \"MeanConfidence\" <= 1)");
                        });
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.DocumentPageTechnicalAnalysis", b =>
                {
                    b.Property<Guid>("DocumentTechnicalAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("HasMeaningfulText")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPageSizedImage")
                        .HasColumnType("boolean");

                    b.Property<int>("ImageCount")
                        .HasColumnType("integer");

                    b.Property<double>("ImageCoverageRatio")
                        .HasColumnType("double precision");

                    b.Property<string>("TechnicalType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TextCharacterCount")
                        .HasColumnType("integer");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer");

                    b.HasKey("DocumentTechnicalAnalysisId", "PageNumber");

                    b.ToTable("DocumentPageTechnicalAnalyses", null, t =>
                        {
                            t.HasCheckConstraint("CK_DocumentPageTechnicalAnalyses_ImageCoverageRatio", "\"ImageCoverageRatio\" >= 0 AND \"ImageCoverageRatio\" <= 1");
                        });
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.DocumentTechnicalAnalysis", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AnalyzedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AnalyzerVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ImageBasedPageCount")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MixedPageCount")
                        .HasColumnType("integer");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer");

                    b.Property<int>("ScannedPageCount")
                        .HasColumnType("integer");

                    b.Property<string>("SourceFileHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TechnicalType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TextBasedPageCount")
                        .HasColumnType("integer");

                    b.Property<int>("UnknownPageCount")
                        .HasColumnType("integer");

                    b.HasKey("DocumentId");

                    b.ToTable("DocumentTechnicalAnalyses", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.DocumentTextSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExtractionMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Unknown");

                    b.Property<bool>("NormalizationChanged")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("NormalizedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedContent")
                        .HasColumnType("text");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("integer");

                    b.Property<int>("RemovedCharacterCount")
                        .HasColumnType("integer");

                    b.Property<int>("SectionIndex")
                        .HasColumnType("integer");

                    b.Property<string>("SectionTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "SectionIndex")
                        .IsUnique();

                    b.ToTable("DocumentTextSections", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.DocumentUnderstanding", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AnalyzedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetectedTitle")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("DocumentSubtype")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double?>("DocumentTypeConfidence")
                        .HasColumnType("double precision");

                    b.Property<double?>("LanguageConfidence")
                        .HasColumnType("double precision");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrimaryLanguageCode")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Subject")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("DocumentId");

                    b.ToTable("DocumentUnderstandings", null, t =>
                        {
                            t.HasCheckConstraint("CK_DocumentUnderstandings_DocumentTypeConfidence", "\"DocumentTypeConfidence\" IS NULL OR (\"DocumentTypeConfidence\" >= 0 AND \"DocumentTypeConfidence\" <= 1)");

                            t.HasCheckConstraint("CK_DocumentUnderstandings_LanguageConfidence", "\"LanguageConfidence\" IS NULL OR (\"LanguageConfidence\" >= 0 AND \"LanguageConfidence\" <= 1)");
                        });
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "UpdatedAtUtc");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.Conversation", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Server.Models.Project", "Project")
                        .WithMany("Conversations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.ConversationMessage", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Server.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.ConversationMessageSource", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Server.Models.ConversationMessage", "ConversationMessage")
                        .WithMany("Sources")
                        .HasForeignKey("ConversationMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConversationMessage");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.Document", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Server.Models.Project", "Project")
                        .WithMany("Documents")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.DocumentChunk", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Server.Models.Document", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.DocumentMetadataEntry", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Server.Models.DocumentUnderstanding", "DocumentUnderstanding")
                        .WithMany("MetadataEntries")
                        .HasForeignKey("DocumentUnderstandingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentUnderstanding");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.DocumentOcrAnalysis", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Server.Models.Document", "Document")
                        .WithOne("OcrAnalysis")
                        .HasForeignKey("AI.DocumentAssistant.Server.Models.DocumentOcrAnalysis", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.DocumentPageOcrResult", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Server.Models.DocumentOcrAnalysis", "DocumentOcrAnalysis")
                        .WithMany("Pages")
                        .HasForeignKey("DocumentOcrAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentOcrAnalysis");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.DocumentPageTechnicalAnalysis", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Server.Models.DocumentTechnicalAnalysis", "DocumentTechnicalAnalysis")
                        .WithMany("Pages")
                        .HasForeignKey("DocumentTechnicalAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentTechnicalAnalysis");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.DocumentTechnicalAnalysis", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Server.Models.Document", "Document")
                        .WithOne("TechnicalAnalysis")
                        .HasForeignKey("AI.DocumentAssistant.Server.Models.DocumentTechnicalAnalysis", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.DocumentTextSection", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Server.Models.Document", "Document")
                        .WithMany("TextSections")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.DocumentUnderstanding", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Server.Models.Document", "Document")
                        .WithOne("Understanding")
                        .HasForeignKey("AI.DocumentAssistant.Server.Models.DocumentUnderstanding", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.Project", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Server.Models.ApplicationUser", "Owner")
                        .WithMany("OwnedProjects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AI.DocumentAssistant.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("AI.DocumentAssistant.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.ApplicationUser", b =>
                {
                    b.Navigation("OwnedProjects");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.ConversationMessage", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.Document", b =>
                {
                    b.Navigation("Chunks");

                    b.Navigation("OcrAnalysis");

                    b.Navigation("TechnicalAnalysis");

                    b.Navigation("TextSections");

                    b.Navigation("Understanding");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.DocumentOcrAnalysis", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.DocumentTechnicalAnalysis", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.DocumentUnderstanding", b =>
                {
                    b.Navigation("MetadataEntries");
                });

            modelBuilder.Entity("AI.DocumentAssistant.Server.Models.Project", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
